/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_androidrust_NativeLib */

#ifndef _Included_com_example_androidrust_NativeLib
#define _Included_com_example_androidrust_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_androidrust_NativeLib
 * Method:    example
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_androidrust_NativeLib_example
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
